### ISSUE TITLE
Possible bug when numP > totalSample

### ISSUE THREAD

**Issue by shaibagon** [varun-nagaraja/BING-Objectness#1]
in function (`Objecness.cpp:624`)

```
Mat Objectness::trainSVM(const vector<Mat> &pX1f, const vector<Mat> &nX1f, int sT, double C, double bias, double eps, int maxTrainNum)
```

If too many positive samples are supplied, `numP` is not adjusted according to the size of `X1f` and a seg fault occurs.

**Comment by varun-nagaraja** [comment]
Hi @shaibagon, I am not the original author of this code. I only added compatibility for OSX and Linux.

I am not sure why this error would occur. You might want to contact the original author at http://mmcheng.net/bing/

**Comment by shaibagon** [comment]
Thanks. I will contact the original author.
